# Generated by Django 5.1.1 on 2024-09-26 08:01

import uuid

import account.utils
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OtpCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=255, verbose_name="E-mail")),
                (
                    "otp_code",
                    models.CharField(
                        blank=True,
                        default=account.utils.create_random_code,
                        editable=False,
                        max_length=6,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("valid_from", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=50, verbose_name="First name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=50, verbose_name="Last name"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="phone number length must be between 8 - 15",
                        max_length=50,
                        validators=[
                            django.core.validators.MinLengthValidator(8),
                            django.core.validators.MaxLengthValidator(15),
                        ],
                    ),
                ),
                (
                    "postal_code",
                    models.IntegerField(
                        help_text="postal code should have more than 5 digits",
                        validators=[django.core.validators.MinLengthValidator(5)],
                        verbose_name="Postal Code",
                    ),
                ),
                ("state", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=50)),
                (
                    "address_line_1",
                    models.CharField(max_length=255, verbose_name="Address first line"),
                ),
                (
                    "address_line_2",
                    models.CharField(max_length=255, verbose_name="Address second line"),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
