# Generated by Django 5.1.1 on 2024-09-26 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_otpcode_is_valid_alter_otpcode_otp_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="otpcode",
            name="valid_from",
        ),
    ]
