# Generated by Django 5.1.1 on 2024-09-26 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_remove_otpcode_valid_from"),
    ]

    operations = [
        migrations.RenameField(
            model_name="otpcode",
            old_name="is_valid",
            new_name="is_active",
        ),
    ]
