# Generated by Django 5.1.1 on 2024-09-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_rename_is_valid_otpcode_is_active"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["email"], name="account_cus_email_32dadd_idx"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["username"], name="account_cus_usernam_de7f4b_idx"),
        ),
    ]
