# Generated by Django 5.1.1 on 2024-09-28 15:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shop", "0002_alter_category_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=10,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(4)],
                        verbose_name="Coupon Name",
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("percentage", "Percentage"), ("fixed", "Fixed")],
                        default="percentage",
                        help_text="Type Of Coupun, percentage or fixed amount",
                        max_length=10,
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="percatage type should be between 1 and 100, and fixed amount max length is 10",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "max_uses",
                    models.PositiveIntegerField(
                        help_text="Maximum number of uses this coupon allows",
                        verbose_name="Max Uses",
                    ),
                ),
                (
                    "max_uses_per_user",
                    models.PositiveIntegerField(help_text="How many times users can use this coupon"),
                ),
                (
                    "max_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Max price of a product that is valid for this coupon",
                        max_digits=10,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=500)),
                ("valid_from", models.DateTimeField()),
                ("valid_to", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ManyToManyField(
                        blank=True,
                        help_text="which category can use thise code",
                        related_name="coupons",
                        to="shop.category",
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        help_text="which products can use thise code",
                        related_name="coupons",
                        to="shop.product",
                    ),
                ),
                (
                    "sub_category",
                    models.ManyToManyField(
                        blank=True,
                        help_text="which sub category can use thise code",
                        related_name="coupons",
                        to="shop.sub_category",
                    ),
                ),
            ],
        ),
    ]
