# Generated by Django 5.1.1 on 2024-09-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupon", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coupon",
            name="max_price",
        ),
        migrations.AddField(
            model_name="coupon",
            name="min_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Min price of a product that is valid for this coupon",
                max_digits=10,
            ),
            preserve_default=False,
        ),
    ]
