# Generated by Django 5.1.1 on 2024-09-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupon", "0002_remove_coupon_max_price_coupon_min_price"),
        ("shop", "0002_alter_category_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="products",
            field=models.ManyToManyField(
                blank=True,
                help_text="which products can use thise code",
                related_name="coupons",
                to="shop.product",
            ),
        ),
    ]
