# Generated by Django 5.1.1 on 2024-09-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupon", "0003_alter_coupon_products"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coupon",
            name="category",
        ),
        migrations.RemoveField(
            model_name="coupon",
            name="products",
        ),
        migrations.RemoveField(
            model_name="coupon",
            name="sub_category",
        ),
        migrations.AddIndex(
            model_name="coupon",
            index=models.Index(fields=["code"], name="coupon_coup_code_e43490_idx"),
        ),
        migrations.AddIndex(
            model_name="coupon",
            index=models.Index(fields=["valid_from", "valid_to"], name="coupon_coup_valid_f_8bd8dc_idx"),
        ),
    ]
