# Generated by Django 5.1.1 on 2024-09-28 20:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_alter_category_is_active"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["slug"], name="shop_produc_slug_76971b_idx"),
        ),
    ]
