# Generated by Django 5.1.1 on 2024-10-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_product_shop_produc_slug_76971b_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="viewed",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
