# Generated by Django 5.1.1 on 2024-10-01 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_product_viewed"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["-created_at"]},
        ),
    ]
