# Generated by Django 5.1.1 on 2024-10-01 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_alter_product_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.CharField(blank=True, help_text="Information about product", max_length=500),
        ),
    ]
