# Generated by Django 5.1.1 on 2024-10-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_product_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True,
                default="category/default.png",
                help_text="Upload Category Image",
                upload_to="category/",
                verbose_name="Category Image",
            ),
        ),
    ]
