# Generated by Django 5.1.1 on 2024-10-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_category_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, help_text="Information about product"),
        ),
    ]
