# Generated by Django 5.1.1 on 2024-10-03 19:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_alter_product_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(max_length=255, unique=True, verbose_name="Safe Url"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="alt",
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AlterField(
            model_name="sub_category",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="sub_category",
            name="slug",
            field=models.SlugField(max_length=255, unique=True, verbose_name="Safe Url"),
        ),
        migrations.AlterUniqueTogether(
            name="productspecificationvalue",
            unique_together={("product", "productspecification")},
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["is_active"], name="shop_produc_is_acti_2257ae_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["viewed"], name="shop_produc_viewed_321202_idx"),
        ),
    ]
