# Generated by Django 5.1.1 on 2024-10-04 06:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_alter_category_name_alter_product_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="favorate",
        ),
        migrations.AddField(
            model_name="product",
            name="wishlist",
            field=models.ManyToManyField(
                blank=True,
                related_name="wishlist_products",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
