# Generated by Django 5.1.1 on 2024-10-09 09:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_remove_product_favorate_product_wishlist"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="title")),
                ("description", models.TextField()),
                (
                    "is_buyer",
                    models.BooleanField(
                        default=False, help_text="Is thise user buy this product"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="shop.product",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["customer", "product"],
                        name="shop_review_custome_eda0d1_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="shop_review_created_2e84c7_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="shop_review_is_acti_90804e_idx"
                    ),
                ],
            },
        ),
    ]
