# Generated by Django 5.1.1 on 2024-10-04 07:20

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0011_rating_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="id",
            field=models.URLField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
