# Generated by Django 5.1.1 on 2024-10-04 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0013_alter_rating_id_alter_review_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
