# Generated by Django 5.1.1 on 2024-10-04 07:22

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0014_alter_review_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
