# Generated by Django 5.1.1 on 2024-10-04 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0015_alter_review_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="is_buying",
            new_name="is_buyer",
        ),
    ]
