# Generated by Django 5.1.1 on 2024-10-04 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0016_rename_is_buying_review_is_buyer"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Rating",
        ),
    ]
