# Generated by Django 5.1.1 on 2024-10-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_alter_deliveryoptions_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="discount_amount",
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
