# Generated by Django 5.1.1 on 2024-10-03 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_alter_order_discount_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentdetails",
            name="order",
            field=models.OneToOneField(
                default="",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="order.order",
            ),
        ),
    ]
