# Generated by Django 5.1.1 on 2024-10-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0006_alter_order_discount_amount_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="total_price_before_coupon",
            new_name="order_price",
        ),
        migrations.AlterField(
            model_name="order",
            name="discount_amount",
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
